# Generated by Django 3.2.12 on 2024-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('object', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
